### ISSUE TITLE
DragonflyBSD support (includes workaround)

### ISSUE THREAD

**Issue by falsifian** [browserpass/browserpass-native#104]
-   Operating system + version: DragonflyBSD (following master)

Following the installation instructions on DragonFly, I ran into two problems:

- `-buildmode=pie not supported on dragonfly/amd64`
  - I fixed this by deleting that flag from `Makefile`
- `"The operating system DragonFly is not supported".` when I try to run `gmake hosts-chromium-user PREFIX=$HOME/.local` 
  - I fixed this by replacing `Linux|*BSD)` `Linux|*BSD|DragonFly)` in the case statement in the Makefile.

Now it seems to work (I successfully got it to fill in a password in Chromium.)

I can try to put together a pull request if you like. I guess you don't want to remove `-buildmode=pie` everywhere, so I'd need to figure out how to enable it conditionally.

**Comment by maximbaz** [comment]
Thanks, please do submit a PR! As for PIE, notice that it's only used for the generic "browserpass" goal and not for OS-specific one, so maybe just create another OS specific target? The genetic one is mostly used for local development and packaging, where GOFLAGS would often be overridden anyway, and for OS specific targets we use very minimal flags, in part also because I don't know which OS support which flags and have no way to test them all.
