### ISSUE TITLE
Microsoft Edge (Linux) - Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by rylancates** [browserpass/browserpass-native#121]
### General information

-   Operating system + version: Fedora Workstation 36
-   Browser + version: Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit)
-   Information about the host app:
    -   How did you install it? `make && sudo make install`
        
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`): 3.0.10
-   Information about the browser extension:
    -   How did you install it? Chrome's store
        
    -   Browserpass extension version as reported by your browser: 3.7.2

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Clone latest release

2. `make && sudo make install`

3. See the error message in the browser extension in Edge

### What should happen?

I'd like this extension to work in Edge :)

### What happened instead?

I received the error message in the Issue Title

**Comment by maximbaz** [comment]
Hello, the error you are getting is because it's not enough to just install Browserpass, every browser has to also be specifically configured - however unfortunately we don't have a configuration yet for the Edge 🙂 If you like to try, you can try to find it or reverse engineer it, and submit a PR once you succeed - look at paths in Makefile for other Chromium derivatives, maybe you will just succeed in guessing 😉 If not you can at least feel free to share your findings in this issue, so that other community members can jump in and also try to help.

**Comment by rylancates** [comment]
@maximbaz I've managed to get this working with the user command by placing the json file in `"$(XDG_CONFIG_HOME)/microsoft-edge/NativeMessagingHosts/$(APP_ID).json`.

The system-wide command is a bit less straight forward.

The directory structure for Edge is sufficiently different to the point I'm not so sure how to proceed.

I was looking for a similar directory to `/etc/opt/chrome/` for Edge, but Edge doesn't appear to install into that path. The nearest I can find for Edge is `/opt/microsoft/msedge/`. Then, I took a chance and placed the `native-messaging-hosts` folder in that directory, but to no effect.

Further:
- I'm not 100% sure what the policies functionality is or does
- I don't have a Mac so I can't attest to the Darwin file paths and instructions

I'd be happy to open a PR with modifications that add support for Linux via the `hosts-edge-user` step, but it would be incomplete support for the browser.

How would you prefer I proceed at this point?

**Comment by rylancates** [comment]
PR #122 opened for discussion

**Comment by maximbaz** [comment]
Thanks for the investigation and for the PR 👍 Will leave the comments there.

> I'm not 100% sure what the policies functionality is or does

It auto-installs browser extension, so that a user doesn't have to get it from Web Store. In the browser extension list, such extension would look a bit different, with "Uninstall" button disabled as it's impossible to remove such extension directly from the browser. You could say, abusing a bit a browser feature of enforcing corporate policies in order to improve user experience of getting the extension to work 🙂

**Comment by maximbaz** [comment]
This has been merged, closing, thanks!
