### ISSUE TITLE
How to configure browser in windows manually?

### ISSUE THREAD

**Issue by ErnestDong** [browserpass/browserpass-native#150]
### General information

-   Operating system + version: WIn10
-   Browser + version: Edge(Chrome)
-   Information about the host app:
    -   How did you install it? by building from source
        
    -   If built from sources, put a commit id (`$ git describe --always`):3.1.0-8-gc661efc
-   Information about the browser extension:
    -   How did you install it? from webstore
        

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?
---
I got a Windows laptop for work without admin privileges. But the official Windows installation of browserpass needs admin right. Therefore I decide to build browserpass from source. But I stuck with no idea of how to configure browsers since `make host-edge-user` returns `The operating system Windows_NT is not supported`. So I wonder how you configure browsers in the installation exe.

### Exact steps to reproduce the problem

1. make browserpass-windows64

2. make host-edge-user

### What should happen?

configure browser

### What happened instead?

```
The operating system Windows_NT is not supported
make: *** [Makefile:265: hosts-edge-user] Error 1
```

**Comment by maximbaz** [comment]
Hello! Like so:

https://github.com/browserpass/browserpass-native/blob/c661efc2ab576f324f76ef33918477b0d2dfc924/windows-setup.wxs#L18-L23

I suppose you will need to use HKCU (current user) since you won't have permissions for the HKLM, and do put the appropriate paths to your binary and json file. Also remember to update your json file itself, to have the correct path inside. Good luck :slightly_smiling_face:

**Comment by ErnestDong** [comment]
very helpful. thank you
