### ISSUE TITLE
No asc files for the source code packages in releases

### ISSUE THREAD

**Issue by wojnilowicz** [browserpass/browserpass-native#152]
Could you start adding .asc files to:
1. Source code (zip)
2. Source code (tar.gz)

as seen in the Releases section?

There is an rpm package for Fedora pending at https://bugzilla.redhat.com/show_bug.cgi?id=2251506 and it currently downloads browserpass-native-3.1.0-src.tar.gz instead, because it has the accompanying browserpass-native-3.1.0-src.tar.gz.asc

**Comment by maximbaz** [comment]
There is in fact asc file for the tarball:

https://github.com/browserpass/browserpass-native/releases/download/3.1.0/browserpass-native-3.1.0.tar.gz.asc

I believe zip archives that Github generates are not reproducible, so it's too cumbersome to sign them, don't use them.

By the way, Fedora _should_ use `src.tar.gz`, because that package is signed and contains all dependencies, so it can be compiled fully offline and thereby reduce risk of tampering with the sources during the build.

**Comment by wojnilowicz** [comment]
Indeed, the asc file exists. Sorry for bothering you.

I believe Fedora uses src.tar.gz archives by default, so it should be all good in this aspect.

**Comment by wojnilowicz** [comment]
I understand that
https://github.com/browserpass/browserpass-native/releases/download/3.1.0/browserpass-native-3.1.0.tar.gz.asc
that you linked is for
https://github.com/browserpass/browserpass-native/releases/download/3.1.0/browserpass-native-3.1.0-src.tar.gz
and I asked for and asc file for
https://github.com/browserpass/browserpass-native/archive/refs/tags/3.1.0.tar.gz
It's considerably smaller.
Could you add an asc file for that?

**Comment by maximbaz** [comment]
The link I shared above is what you asked - doesn't it work for you?

**Comment by maximbaz** [comment]
![image](https://github.com/user-attachments/assets/bc9eb205-5e8e-4fa5-8ba9-317f332d196e)

**Comment by wojnilowicz** [comment]
All good with you first link. I just missed that it had no "src" in its name :D 
Sorry for bothering you.

**Comment by maximbaz** [comment]
Haha no worries, enjoy :)
