### ISSUE TITLE
homebrew formula for macOS

### ISSUE THREAD

**Issue by Amar1729** [browserpass/browserpass-native#45]
I currently have browserpass as one of the formulae in my [personal tap](https://github.com/amar1729/homebrew-formulae/tree/master), but it might look better/more official if were hosted in the browserpass org.

It could just be a repo: `browserpass/homebrew-tap` which would pretty much just have a readme and `browserpass.rb` in it.

I can help manage and test it if you think it's something you want, otherwise you could just add my tap to the list of packages for browserpass.

**Comment by maximbaz** [comment]
I think it would be best if we keep distributions outside of the org for now, especially because no Browserpass maintainer actually uses macOS. I don't want to give people a false sense of extra promised stability due to the tap being located under the Browserpass org.

I'm happy to add your tap to the README if you are planning to keep it up to date 😉 Will do tomorrow.

Thanks again for creating it, and for helping to make the experience for macOS better in general!
