### ISSUE TITLE
automate windows installation

### ISSUE THREAD

**Issue by razic** [browserpass/browserpass-native#48]
i'd like to get an idea of what it would take to automate a windows installation and maybe contribute a pull request.

prior to v3, if i remember correctly, there were two installation scripts `install.{ps1,sh}` accommodating both windows and unix users respectively.

i haven't set up my installation on my linux yet, but i set it up on my windows and noticed there was a couple mentions basically saying theres no makefile or automation for installation for windows.

while [browser]pass is targeted toward technical audience, i still think we can improve the workflow for windows users. a couple questions i have are:

* am i correct in understanding that previously there was an automation for windows installation, whereas now there is not?

* if the above is correct, what was the reason for leaving windows out of the installation. is it just that you don't have a maintainer who uses windows? does that mean that you use to have a maintainer that used windows?

* unless i'm missing something, recreating the `install.ps1` script for windows should be fairly straightforward, right?

**Comment by maximbaz** [comment]
An improvement for Windows users is definitely welcome!

> am i correct in understanding that previously there was an automation for windows installation, whereas now there is not?

Yes and no, `install.ps1` existed, but I'd say it provided a very limited subset of installation options. On Windows there are two ways of installing the application ("usual" and WSL), Makefile (for other OS) provides install targets for 5 browsers, for each of which we have "User" and "Global" installation, plus there are 4*2 ways of installing policies. The `install.ps1` supported only "usual" installation and 2 browsers, no policy files.

> if the above is correct, what was the reason for leaving windows out of the installation. is it just that you don't have a maintainer who uses windows?

Basically, yes.

> does that mean that you use to have a maintainer that used windows?

The `install.ps1` was contributed by a user in early days of v2, you have a chance to contribute something even better for v3 😉 

> unless i'm missing something, recreating the install.ps1 script for windows should be fairly straightforward, right?

Depends on how much feature-parity you want to achieve with Linux/macOS installation. 

In my opinion, a good start would be to automate [Install on Windows](https://github.com/browserpass/browserpass-native#install-on-windows) and [Install on Windows through WSL](https://github.com/browserpass/browserpass-native#install-on-windows-through-wsl) steps, so that a binary is installed in some location, and path to it is correctly set in json files. That's the most annoying part.

If you know how to make a proper GUI installer, that would be the best. If not, we can settle for a `install-windows.ps1` script.

I propose that an installer/script should install both "usual" and "WSL" versions, so that we can replace both those sections in README with simply "Run an installer". It could for example install "usual" browserpass into `C:\Program Files\Browserpass\` and WSL version in `C:\Program Files\Browserpass (WSL)\` (e.g. I don't think `browserpass-wsl.bat` has to exists exclusively in `%localappdata%`, we can put it in `Program Files`.

After we automate the above, [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers-on-windows) could be a second step, as you've seen it's just two lines of PowerShell, the biggest problem is to actually figure out the correct paths on Windows for various browsers, so far I only know paths for Google Chrome and Firefox, and only because I took them from the user-contributed script from v2 - but I guess these two are the most popular ones anyway 🙂

**Comment by razic** [comment]
> In my opinion, a good start would be to automate Install on Windows and Install on Windows through WSL steps, so that a binary is installed in some location, and path to it is correctly set in json files. That's the most annoying part.
>
> If you know how to make a proper GUI installer, that would be the best. If not, we can settle for a install-windows.ps1

i've never made a gui installer before and to be honest not even a powershell script but i don't think that would be too much of a problem. i'll start with the script. 

> I propose that an installer/script should install both "usual" and "WSL" versions, so that we can replace both those sections in README with simply "Run an installer". It could for example install "usual" browserpass into C:\Program Files\Browserpass\ and WSL version in C:\Program Files\Browserpass (WSL)\ (e.g. I don't think browserpass-wsl.bat has to exists exclusively in %localappdata%, we can put it in Program Files.

:+1: 

> After we automate the above, Configuring browsers could be a second step, as you've seen it's just two lines of PowerShell, the biggest problem is to actually figure out the correct paths on Windows for various browsers, so far I only know paths for Google Chrome and Firefox, and only because I took them from the user-contributed script from v2 - but I guess these two are the most popular ones anyway slightly_smiling_face

i'll try to figure it out. should be easy enough to install the various browsers and search for the registry keys

**Comment by razic** [comment]
so i've been thinking about wsl. essentially, i was going to install wsl myself to see what the process would be like.

i googled how to install wsl, and some [good docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10) from microsoft came up. except there are no official docs from microsoft for installing distros that arent in the microsoft app store.

so i did a little bit more googling, specifically for an arch image built for wsl. now while i did find some open source projects, i also found this:

https://lists.archlinux.org/pipermail/arch-dev-public/2018-January/029144.html

i use linux on a daily basis for work, and i mostly use windows for gaming. as much as i'd love to see support for linux based subsystems in windows, i unfortunately agree with much of what is said in the comments on that thread.

i don't want to throw the idea out completely, but even the person who originally sparked interest in the idea mentions in the first sentence this is probably not worth supporting https://github.com/browserpass/browserpass-legacy/issues/192

that being said, i'm a bit reluctant to provide an installer that accommodates both wsl and non-wsl installs. it seems like a convoluted process.

for one, supporting a native install covers all grounds. this means we can support all windows installs. having an additional support for wsl, doesn't give us much.

the user mentions in the article that they do not wish to have a second copy of their password store, which is the only reason they sought out bridging browserpass plugin in windows to their wsl.

without the graphical pinentry within windows to help facilitate the gpg process, the user has to load their key into the gpg-agent manually via wsl beforehand.

another user commented that they were able to automate the process using https://github.com/diablodale/pinentry-wsl-ps1. looking at the repo, its basically a bash script that invokes a gui in windows and acts as a drop-in replacement for other pinentry programs.

with all that being said, i don't really think its a good idea to support wsl based installation. it makes things more complicated than it needs to be.

if the problem is that the user wishes to store their password-store on their "wsl file-system" without duplicating it onto their "windows file-system", we may be able to accomplish that already. it seems like windows does support file access from windows itself into wsl based filesystem. i haven't tested it, but theoretically, that person could have just installed https://www.gpg4win.org/ and configure their browser extension to point to the password store in their "wsl filesystem". while this may seem like a relatively new feature and requires windows version 1903 and up, these docs seem promising https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/.

@maximbaz what do you think?

**Comment by maximbaz** [comment]
Thanks for looking into it!

First of all, have you seen #59? 🙂 cc @tillkrischer

It's hard for me to judge whether supporting WSL really makes sense, so let me just ping everyone I know who uses it: @jtsymon, @frebib, @kpengboy, @jakubtopic.

You are right that the main reason to use WSL setup is just to avoid duplicating password store on two file systems, if this is no longer an issue, perhaps we don't need to support this then. Could some of you please confirm whether it actually true these days?

That being said, I never wanted WSL to complicate the installer, all I wanted is to install several more files. If what you discovered is true and people no longer need to use WSL wrapper, I would also prefer to have installer only do the "regular" installation - especially because manipulating registry becomes much simpler, as you don't need to ask people if they want to configure browsers for "regular" or WSL setup.

**Comment by kpengboy** [comment]
I actually use WSL (or properly speaking, GNU/WSL) to avoid having to
install another copy of GPG in the Win32 environment. For me, it didn't
have to do with deduplicating the password store.

**Comment by razic** [comment]
@kpengboy where do you store your gpg key and do you have more than one
device you use pass on, ie phone or different computer?

**Comment by maximbaz** [comment]
I've updated the latest release to include MSI file for Windows 🙂 

WSL remains manual installation, for example because MSI will not be able to write inside the WSL file system anyway.
