### ISSUE TITLE
Does not install on FreeBSD

### ISSUE THREAD

**Issue by tehpeh** [browserpass/browserpass-native#52]
There's an issue when installing version 3.0.6 release of FreeBSD. I haven't investigated any further.

```
$ make BIN=browserpass-freebsd64 configure
-i 's|"path": ".*"|"path": "'"/usr/bin/browserpass-freebsd64"'"|' browser-files/chromium-host.json
/bin/sh: -i: not found
*** Error code 127

Stop.
```

**Comment by maximbaz** [comment]
Interesting, it seems you don't have `sed` installed on your computer - `make configure` is using this tool to put correct path to the binary in the host files.

Would you be interested to investigate this further? Is this usual that FreeBSD users don't have `sed` installed? Is the package called `sed`? I can add this to README saying that this is a required dependency for the installation. We had a similar issue with macOS users, turned out they need to install a package called `gnu-sed`.

If you don't have time, just edit the `hosts-*.json` files manually and put `/usr/bin/browserpass-freebsd64` there manually, then proceed with the `install` step.

**Comment by tehpeh** [comment]
Thanks @maximbaz. FreeBSD also does not have GNU `sed` by default. The BSD `sed` command line options are a little different.

We can either install the `gsed` package or modify the Makefile. I will investigate and get back to you.

**Comment by maximbaz** [comment]
Thank you! `gsed` would probably be simplest just because Makefile is already tailored for this for macOS, but if you figure out how to improve Makefile so that it works equally well with GNU and BSD `sed` (and we would remove the hack of detecting `gsed`) that would be just awesome 😉

**Comment by tehpeh** [comment]
Ok, so FreeBSD will require `gsed`, `gmake`, and `coreutils` packages, and `PREFIX=/usr/local`. I'll add these to the Readme.
