### ISSUE TITLE
Windows MSI creates registry entries under `WOW6432Node`

### ISSUE THREAD

**Issue by ratinoxone** [browserpass/browserpass-native#65]
OS: Windows 10/1809
Browsers: Firefox, Chrome, Chromium, Brave
Browserpass Version: 3.0.6, Windows MSI.

Symptoms:
MSI installer unpacks everything into C:\Program Files\Browserpass. The json files are not moved into C:\Program Files\Browserpass\browser-files and the NativeMessagingHost registry entries are not created.

Error message:
Error: Error: Attempt to postMessage on disconnected port

Workaround:
Mostly the full manual process: Create C:\Program Files\Browserpass\browser-files, move json files to this directory, and run the PowerShell commands to create the registry entries.

**Comment by maximbaz** [comment]
Hey!

It is expected that layout of files is slightly different on Windows, there is no `browser-files` subfolder, everything is placed directly in `C:\Program Files\Browserpass`.

Layout of files is specified [here](https://github.com/browserpass/browserpass-native/blob/master/windows-setup.wxs):

```
C:\Program Files\Browserpass\
    browserpass-windows64.exe
    chromium-host.json
    chromium-policy.json
    firefox-host.json
    README.md
    LICENSE
```

It is also true that MSI does not create registry entries for Chromium and Brave browsers (only FF and Google Chrome), simply because nobody knows the correct paths 🙂 If you know them, feel free to send a PR (please only make sure to test twice, because I don't have a Windows box to test that those paths indeed are correct).

Currently created registries:

```
HKLM:\\Software\Google\Chrome\NativeMessagingHosts\com.github.browserpass.native -> C:\Program Files\Browserpass\chromium-host.json
HKLM:\\Software\Mozilla\NativeMessagingHosts\com.github.browserpass.native -> C:\Program Files\Browserpass\firefox-host.json
```

**Comment by ratinoxone** [comment]
Searched for NativeMessagingHosts through the entire registry (from previous manual installation), removed all instances.

Install MSI. Extension does not work for any browser. Repair MSI. Extension still does not work. Uninstall MSI. Install MSI. Extension still does not work. Repair MSI. Extension still does not work.

Searched registry for NativeMessagingHosts. There are none. MSI install/repair did not create any registry entries.

Manually created registry entries using the PowerShell commands. Verified registry entries by eye.

Extension still reports "Attempt to postMessage on disconnected port" error on all browsers I tested.

Manually created browser-files directory and moved json files into this directory.

Plugin now works on Firefox, Chrome and Brave. Executable is not looking for files where the spec says they should be.

Chromium and Brave use Google Chrome's NativeMessagingHosts registry entries.

**Comment by maximbaz** [comment]
That's strange, sorry I don't know what might be wrong, I know at least 3 people who successfully installed Browserpass using this MSI on Windows 10 and it worked perfectly.

Can you try to enable verbose logging and paste it here? Something like this should do the trick I think:

```
msiexec /i browserpass.msi /L*V browserpass-install.log
```

> Manually created registry entries using the PowerShell commands. Verified registry entries by eye.
> Extension still reports "Attempt to postMessage on disconnected port" error on all browsers I tested.
> Manually created browser-files directory and moved json files into this directory.
> Plugin now works on Firefox, Chrome and Brave.

This means the registry entries are configured to look for `browser-files` directory, i.e. instead of this:

```
HKLM:\\Software\Google\Chrome\NativeMessagingHosts\com.github.browserpass.native -> C:\Program Files\Browserpass\chromium-host.json
```

Your registry looks like this:

```
HKLM:\\Software\Google\Chrome\NativeMessagingHosts\com.github.browserpass.native -> C:\Program Files\Browserpass\browser-files\chromium-host.json
```

Can you confirm? It doesn't really matter where the json files are located, as long as their path is correctly reflected in the registry. MSI puts them in `C:\Program Files\Browserpass`, but MSI is also configuring registry to look into `C:\Program Files\Browserpass`.

> Chromium and Brave use Google Chrome's NativeMessagingHosts registry entries.

This is surprising, but excellent, seems we don't need to do anything extra in MSI to add support for Chromium and Brave browsers 🙂

**Comment by ratinoxone** [comment]
Can confirm the path problem is my own doing (I copy-pasted the PowerShell commands from the old README). I'll see if I can get anything useful out of verbose logging this evening.

**Comment by maximbaz** [comment]
Could it be that when MSI is executed, it doesn't have permission to write to HKLM? Can you execute it as administrator?

According to the log you attached, the registry entries have been created successfully...

```
Executing op: ActionStart(Name=WriteRegistryValues,Description=Writing system registry values,Template=Key: [1], Name: [2], Value: [3])^M
Executing op: ProgressTotal(Total=2,Type=1,ByteEquivalent=13200)^M
Executing op: RegOpenKey(Root=-2147483646,Key=Software\Google\Chrome\NativeMessagingHosts\com.github.browserpass.native\,,BinaryType=0,,)^M
Executing op: RegAddValue(,Value=C:\Program Files\Browserpass\chromium-host.json,)^M
Executing op: RegOpenKey(Root=-2147483646,Key=Software\Mozilla\NativeMessagingHosts\com.github.browserpass.native\,,BinaryType=0,,)^M
Executing op: RegAddValue(,Value=C:\Program Files\Browserpass\firefox-host.json,)^M
```

Given that nobody else is reporting similar issues, I think the problem is somehow on your side, but would be curious to understand what is the root cause.

**Comment by erayd** [comment]
> Given that nobody else is reporting similar issues, I think the problem is somehow on your side...

Do we have any idea how large (or small) our Windows user base actually is? I know the total is thousands, but do either of the extension stores give us any OS metrics?

**Comment by maximbaz** [comment]
Chrome webstore gives us nothing, Firefox webstore has some stats:

![image](https://user-images.githubusercontent.com/1177900/57331795-c08b8180-7119-11e9-8080-54f43ba1616e.png)

In real life I only know two people who use Browserpass on Windows, both of them used this MSI to get it up and running with no issues.

**Comment by ratinoxone** [comment]
I am running as an administrator user so that's not it.

Are you certain that the users who are using the MSI did not previously install manually and leave the old registry entries in place? If so then the old HKLU entries are preventing the problem. Which as far as I can tell is that the 64-bit MSI is installing as a 32-bit application on a 64-bit system which is a bug:

https://support.microsoft.com/en-us/help/2582176/registry-key-wow6432node-may-be-listed-in-system-registry-on-32bit-x86

"This registry key is typically used for 32 bit applications on 64 bit machines. If they are present on x86 machines, they do not cause any issues as they are not used. "

The WOW6432Node key is only used by 32-bit applications. 64-bit applications ignore it.

**Comment by maximbaz** [comment]
I can only speak for the two people I know personally, they installed Browserpass v3 for the first time using this MSI.

They both use Windows 10 64bit, and one of them has just confirmed to me that yes, they indeed have Browserpass entries in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node`, and that those entries are the ones that are used by Google Chrome (removing them breaks Browserpass, re-adding fixes).

But I agree with you, it does sound wrong to use `WOW6432Node` folder, even though it works for some people. 

A PR would be very welcome, would you like to investigate how to fix creating registry entries? The current code is right here:

https://github.com/browserpass/browserpass-native/blob/bc473160f9e97de956b776789b4dc4541d1ee116/windows-setup.wxs#L18-L23

**Comment by ratinoxone** [comment]
The problem is that the MSI is 32-bit, or something the MSI does is 32-bit, which causes the Windows installer system to map HKLM\SOFTWARE\WOW6432Node over HKLM\SOFTWARE. The paths in the wxs file are correct. The MSI's target architecture is wrong. You need to fix the build.

**Comment by maximbaz** [comment]
Unfortunately I don't really know what it means to fix the build, the wxs template and the command I use to compile MSI are in the repo (in Makefile), so if someone is interested to help out, patches welcome :)

**Comment by mattdconnell** [comment]
Is the issue possibly being caused by the explicit specification of `ProgramFiles64Folder` (rather than just, say `ProgramFilesFolder`, for example) [here](https://github.com/browserpass/browserpass-native/blob/bc473160f9e97de956b776789b4dc4541d1ee116/windows-setup.wxs#L9)?

This is just a wild guess; as I stated [elsewhere](https://github.com/browserpass/browserpass-extension/issues/156) I don't know much of anything about building for Windows platforms.

**Comment by maximbaz** [comment]
I think (untested) that by using `ProgramFiles64Folder` we get the correct `C:\Program Files\` on a 64bit Windows, while by using `ProgramFilesFolder` we would end up with an incorrect `C:\Program Files (x86)\` folder path...

**Comment by ratinoxone** [comment]
No. It's not the install path. The MSI installer creates the correct 64-bit paths in the registry but creates them in the incorrect 32-bit registry hive. There are two ways this can happen.

The first is by explicitly referencing the 32-bit hive from a 64-bit executable: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node. windows-setup.wxs does not do this.

The second is from a 32-bit executable: 64-bit Windows maps HKEY_LOCAL_MACHINE\SOFTWARE to HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node for 32-bit executables. That is, the executable sees "HKEY_LOCAL_MACHINE\SOFTWARE" while the actual registry hive is "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node".

The code is correct. The problem is whatever is being used to package the MSI is (I think) incorrectly configured to create 32-bit packages. You need to correct the packager and rebuild the packages.

**Comment by maximbaz** [comment]
`wixl` is being used to package the MSI, here's the full reference:

https://github.com/browserpass/browserpass-native/blob/faaa99feb4423739a3c176a5759f4d2fb038b12f/Makefile#L78-L83

**Comment by maximbaz** [comment]
Seems like this isn't actionable and there are no obvious alternatives to use, will close the ticket, but feel free to continue the discussion or make a PR if you think this can be improved.
