### ISSUE TITLE
Add a release tarball with the Go dependencies vendored in it

### ISSUE THREAD

**Issue by Cogitri** [browserpass/browserpass-native#70]
It'd be nice if it was possible to build browserpass without internet access and would make it easier to build it. Also, this would enable version locking and as such would make builds reproducible (or maybe that's already possible and I just don't now it because I don't know Go too well).

See https://github.com/alpinelinux/aports/pull/7475 where I package browserpass for Alpine Linux, which requires reproducible builds.

**Comment by maximbaz** [comment]
As replied in that thread, reproducible builds are not an issue thanks to Go modules (see `go.sum` file).

As to hosting yet another source archive with dependencies, I don't think it's really needed - I used to do that in the past when I used a third-party tool to manage dependencies (because I wanted to avoid you as an Alpine packager to install that tool), but now that dependencies can be fetched using Go itself, I don't think it's needed.

I don't think building without Internet is a real concern, as you need to fetch the archive via Internet anyway - but let me know if you feel strongly about it, and what would be the examples where users won't be able to use Go to fetch dependencies.

Thanks again for packaging for Alpine 🎉
