### ISSUE TITLE
Go with GVM: make: *** No rule to make target '*.go'

### ISSUE THREAD

**Issue by st-leo** [browserpass/browserpass-native#78]
### General information

I'm new to Go. I have gvm installed, and prior to following the installation steps I ran `gvm use` so the Go paths were available. Still, it looks that the Makefile can't find go binaries.

-   Operating system + version: Ubuntu 19.04
-   Browser + version: Chromium 74
-   Information about the host app:
    -   How did you install it?
       downloaded a pre-built binary
    -   If installed an official release, put a version (`$ browserpass --version`): n/a
    -   If built from sources, put a commit id (`$ git describe --always`): n/a

### Exact steps to reproduce the problem

1. Download and extract https://github.com/browserpass/browserpass-native/releases/download/3.0.6/browserpass-linux64-3.0.6.tar.gz

2. Following https://github.com/browserpass/browserpass-native#install-manually, running `sudo make BIN=browserpass-linux64` returns the following output: `make: *** No targets specified and no makefile found.  Stop.`

### What should happen?

Installation 

### What happened instead?

Error

**Comment by maximbaz** [comment]
Hey, you have to first `cd` into the folder containing the Makefile

**Comment by st-leo** [comment]
Right, sorry if I wasn't clear, but I'm in that dir already.

```bash
leo@leo-msi:~/Downloads/browserpass-linux64-3.0.6 $ ls
browser-files  browserpass-linux64  LICENSE  Makefile  README.md
leo@leo-msi:~/Downloads/browserpass-linux64-3.0.6 $ sudo make BIN=browserpass-linux64
make: *** No rule to make target '*.go', needed by 'browserpass'.  Stop.
```

**Comment by maximbaz** [comment]
Ah, I was confused by the different error message in the body of the first comment :slightly_smiling_face: 

Are you trying to compile the app yourself, or install the pre-built binary? In the latter case, you are missing the make goals like "configure" or "install". You don't even need to have Go installed, because the binary is pre-compiled by me and all you need to do is to install it in a proper location.

In case you actually want to compile the binary yourself, you have to download a different archive (with source code) and follow the [Building the app](https://github.com/browserpass/browserpass-native#building-the-app) section first.

Let me know if this helps :slightly_smiling_face:

**Comment by st-leo** [comment]
Great, that worked, thanks! Strange because I was sure I had ran `configure` already. Anyway, closing this.

**Comment by maximbaz** [comment]
Happy to help, enjoy :tada:
