### ISSUE TITLE
Unable to install broserpass on ubuntu

### ISSUE THREAD

**Issue by kirtangajjar** [browserpass/browserpass-native#85]
### General information

-   Operating system + version: Ubuntu 18.04
-   Browser + version:
-   Information about the host app:
    -   How did you install it?
Via package manager
-   Information about the browser extension:
    -   How did you install it? 
        chrome store
    -   Browserpass extension version as reported by your browser: 3.4.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section? Yes

---

### Exact steps to reproduce the problem

I tried to install it in debian with following commands
```
sudo apt build-dep browserpass
sudo apt source browserpass --compile
```
### What should happen?

I should find `.deb` file of both Browserpass extension and extension host.

### What happened instead?

I found only `webext-browserpass_2.0.11+dfsg-2_amd64.deb`.

Also, I tried to build native extension host with docker:
```
docker build -t browserpass-native .
docker run --rm -v "$(pwd)":/src browserpass-native all
```
This indeed created a `browserpass` binary, but when I ran it,
```
./browserpass -v       
DEBU[2020-01-03T13:23:58+05:30] Starting browserpass host app v3.0.6         
```
Now even after starting it, the chrome extension is not able to detect it:
```
Error: Error: Specified native messaging host not found.
```

**Comment by erayd** [comment]
The source package you are building is ancient; 2.0.11 is no longer supported, and hasn't been for a long time. Why are you building this, and how is it related to your problem?

You mention to followed the 'configure browsers' section - what did you actually do there? Your steps to replicate don't actually mention any of that part, and that's where your problem is - your browser isn't correctly configured to find the host app.

Finally, you mention "...even after starting it, the chrome extension is not able to detect it." The native host is not a persistent process; running it manually will not achieve anything. It's actually launched by the browser reach time the extension needs to do something with the password store.

**Comment by kirtangajjar** [comment]
@erayd Sorry for the trouble. I was not familiar much with compiling go packages and the README steps looked a little complicated, but finally I managed to get it to work.

Here are the steps for anyone who stumbles upon it in future:
```
mkdir -p ~/go/src && cd ~/go/src
export GOPATH=$(pwd)
go get github.com/browserpass/browserpass-native
cd github.com/browserpass/browserpass-native
make BIN=browserpass-linux64 configure 
make BIN=browserpass-linux64 browserpass-linux64
sudo make BIN=browserpass-linux64 install 
make hosts-chrome-user
```

**Comment by juliangaal** [comment]
slightly revised:
```bash
go get github.com/browserpass/browserpass-native
cd $GOPATH/src/github.com/browserpass/browserpass-native
make BIN=browserpass-linux64 configure 
make BIN=browserpass-linux64 browserpass-linux64
sudo make BIN=browserpass-linux64 install 
make hosts-<browser>-user
```
