### ISSUE TITLE
Error: Unable to fetch and parse login fields

### ISSUE THREAD

**Issue by siwan05** [browserpass/browserpass-native#86]
### General information

-   Operating system + version:
-   Browser + version:
-   Information about the host app:
    -   How did you install it?
        
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        
    -   Browserpass extension version as reported by your browser:

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1.

2.

3.

**Comment by erayd** [comment]
Closing, because this issue contains zero information and the subject line appears to be a common problem that's already addressed by the documentation.

**Comment by siwan05** [comment]
Accidentally created before filling out all info. Ok will browse documentation.

**Comment by erayd** [comment]
> Accidentally created before filling out all info. Ok will browse documentation.

Not a problem; happens to the best of us sometimes! The specific section the docs that addresses your issue is [here](https://github.com/browserpass/browserpass-native#configure-browsers). Feel free to ask further if you get stuck, and I can reopen the issue for you.

**Comment by siwan05** [comment]
The weird thing is that this issue started happening all of a sudden. 
If I 1) open a terminal 2) pass XXX 3) write GPG password 4) attempt to fetch any password through browserpass and Brave then it works fine. 

But if I fully close that terminal and attempt to to fetch any password the same way in Brave then I get
`Error: Unable to fetch and parse login fields: Error: {
    "status": "error",
    "code": 24,
    "version": 3000006,
    "params": {
        "action": "fetch",
        "error": "Error: exit status 2, Stderr: Warning: Failed to set locale category LC_NUMERIC to en_SE.\nWarning: Failed to set locale category LC_TIME to en_SE.\nWarning: Failed to set locale category LC_COLLATE to en_SE.\nWarning: Failed to set locale category LC_MONETARY to en_SE.\nWarning: Failed to set locale category LC_MESSAGES to en_SE.\ngpg: decryption failed: No secret key\n",
        "file": "web/github.com/siwan05.gpg",
        "message": "Unable to decrypt the password file",
        "storeId": "default",
        "storeName": "pass",
        "storePath": "/Users/dennissievertz/.password-store"
    }
}`

**Comment by erayd** [comment]
OK, that's not the issue I thought it was - that does look like another common issue though. It means that you don't have a proper pinentry configuration on your system. What are you using for gpg pinentry?

**Comment by erayd** [comment]
You may also find [this](https://github.com/browserpass/browserpass-native#hints-for-configuring-gpg) section of the docs useful.

**Comment by maximbaz** [comment]
Yeah, this definitely means your pinentry is not configured

**Comment by siwan05** [comment]
Ok, thanks for helping!

Well I have pinentry installed and I have pointed to it in my gpg-agent.conf file as:
`pinentry-program /usr/local/opt/pinentry-curses`

Is there anything else that I need to do? This has worked for me without further config for years on multiple laptops, just started now during Christmas break with my latest one.

**Comment by siwan05** [comment]
Looking through the documentation you linked it mentions 
`If Browserpass is unable to locate the proper gpg binary, try configuring a full path to your gpg in the browser extension settings or in .browserpass.json file in the root of your password store:`

But I don't have a .browserpass.json file in the root of your password store. How would I go around to creating that file?

**Comment by erayd** [comment]
> pinentry-program /usr/local/opt/pinentry-curses

`pinentry-curses` is unsuitable, because it's a terminal app, and (unless you create some sort of wrapper around it) cannot pop up on demand when gpg-agent wants you to unlock things. It's fine when you're using a shell already (because gpg-agent will just display the pinentry there), but not for GUI applications that may cause pinentry to be spawned in the background.

If you configure a GUI pinentry app, then it should work correctly. Alternatively, configure a usefully long timeout for gpg-agent and just manually unlock the key in the terminal first. That's not as secure though; configuring a GUI pinentry is better than just leaving an open session.

> This has worked for me without further config for years on multiple laptops, just started now during Christmas break with my latest one.

How were you previously prompted for your PIN / key password? Pinentry-curses is incapable of prompting you anywhere other than the terminal session you're already in.

> If Browserpass is unable to locate the proper gpg binary...

That's not the problem in your case. The error indicates that it can see `gpg` just fine.

> But I don't have a .browserpass.json file in the root of your password store. How would I go around to creating that file?

It's just a JSON file; you can create it with any text editor. The contents is just a standard object. Configurable options are documented [here](https://github.com/browserpass/browserpass-extension#options).

**Comment by maximbaz** [comment]
Thanks for the replies @erayd 👍 

I have explicitly mentioned `pinentry-tty` and `pinentry-curses` in README now, and I copied over this specific FAQ entry from `browserpass-extension` to `browserpass-native`, so that it's even easier to discover in the future: https://github.com/browserpass/browserpass-native#error-unable-to-fetch-and-parse-login-fields

@siwan05 do let us know if you still experience some issues, but hopefully after you configured any pinentry that has GUI things started to work well for you again 👍

**Comment by siwan05** [comment]
Sorry I thought I replied earlier here, my bad!

I managed to solve it by simply removing and re-adding my key to GPG keychain and then rebooting the laptop, not sure why it solved it but works like a charm now!

I realised why it hasn't been an issue before - It has never required a password when fetching, not through terminal nor browserpass

**Comment by i2** [comment]
> `pinentry-curses` is unsuitable, because it's a terminal app, and (unless you create some sort of wrapper around it) cannot pop up on demand when gpg-agent wants you to unlock things. It's fine when you're using a shell already (because gpg-agent will just display the pinentry there), but not for GUI applications that may cause pinentry to be spawned in the background.

@erayd I am interested in this wrapper to force GUI apps to use pinentry-tty or pinentry-console. Would you please point me in the right direction to achieve this? Thank you!

Apologies for commenting on old discussion, but this seems to be the most accurate place to post (and I didn't want to add clutter).

**Comment by erayd** [comment]
@i2 Where are you stuck? Note that I am not referring to an *existing* wrapper script above (so there's not really anything I can provide a link for), but rather to an approach that one might use to solve the issue - i.e. that you can *write* a wrapper.

**Comment by i2** [comment]
@erayd I realized there might not be a wrapper ready-made out there.

I know that I can install a GUI package for pinentry (like gtk, wsl, etc.) but I was wondering if it's possible to get away with just pinentry-tty / console for both terminal based and gui based inquiries.
So here is what I'd like: When browserpass inquires a password, gpg-agent blah blah (from GUI), somehow just not need pinentry gui process to be available and running.

**Comment by i2** [comment]
@erayd I realized there might not be a wrapper ready-made out there.

I know that I can install a GUI package for pinentry (like gtk, wsl, etc.) but I was wondering if it's possible to get away with just pinentry-tty / console for both terminal based and gui based inquiries.
So here is what I'd like: When browserpass inquires a password, gpg-agent blah blah (from GUI), somehow just not need pinentry gui process to be available and running.

**Comment by erayd** [comment]
@i2 You'll need to be using gpg-agent. If you set a timeout in your gpg config, then entering the PIN in the console will allow everything else that talks to the agent to also use the key (without triggering pinentry again) until the timeout expires.

Where the wrapper comes in is if you need your GUI app to somehow spawn the console pinentry.

What is it that you are actually trying to achieve? Using GUI apps, but wishing to avoid GUI pinentry, is a very unusual use-case. Are you able to expand on why you need this?

**Comment by erayd** [comment]
For what you are describing, you'll need to do the following:

1. Set `pinentry-program` in `gpg-agent.conf` to point at your wrapper.
2. Your wrapper needs to:
  1. Read pinentry commands from `gpg-agent` on stdin;
  2. Spawn a terminal somewhere, or connect to one you already have around;
  3. In that terminal, spawn `pinentry-console` and pipe the input from `gpg-agent` to it;
  4. Receive stdout from `pinentry-console` and pipe it back to `gpg-agent`.

Note that it is a two-way protocol; so you'll need to connect the pipes properly rather than just buffering output.

I'm still confused *why* you want to do this... what is wrong with simply using a normal GUI pinentry? Using a console one instead, the way you are describing, isn't *"keeping it minimal"*. Doing that actually adds a bunch of complexity, because you have to implement all that extra communication and add extra dependencies into the pipeline.

**Comment by i2** [comment]
@erayd right, sorry anywhere I said `pinentry-console` I meant `pinentry-tty`.

Honestly, it's just to quench my curiosity that was ignited by the comment up there about `wrapper` and `if you know what you're doing`. Plus I like minimalism `suckless.org`-ness, but true I get what you mean by adding complexity.
