### ISSUE TITLE
Possibility of running on Android?

### ISSUE THREAD

**Issue by ndrewtl** [browserpass/browserpass-native#87]
Hi! I'm a big fan of this project, and I wanted to say thanks again for creating it. I wanted ask about the possibility of running the native client on Android. Doing so would probably mean creating an entirely different codebase in the form of an Android app. But as Android is Linux, it would seem very possible to support the native client's protocol in such a way as to interact with say, the extension running on Android Firefox. GnuPG support for Android via [OpenKeychain](https://github.com/open-keychain/open-keychain) is very good, and similar apps like [Android Password Store](https://github.com/android-password-store/Android-Password-Store) already use it to implement `pass` support. Have you considered creating an Android client?

I'm pretty busy right now. But if I ever get the time, I would love to go about seeing if this is possible. Is there a place I could look to get a formal description of the native client protocol, to see if I could implement it?

Thanks again for making this awesome software!

**Comment by erayd** [comment]
To the best of my knowledge, this isn't possible. Android browsers don't generally provide a mechanism for browser extensions to communicate with native binaries, if your browser even allows extensions at all - many don't. However, my knowledge of that platform is far from exhaustive, and there is plenty I don't know, so I may simply be unaware of the possibility.

You are welcome to take a crack at it if you would like - the protocol is documented [here](https://github.com/browserpass/browserpass-native/blob/master/PROTOCOL.md).

**Comment by maximbaz** [comment]
Hey, thanks for the kind words and the idea 🙂 

Implementing a native host itself isn't a very big problem, the main issue is that no browser that I know of supports native messaging protocol - Firefox for Android certainly doesn't:

![image](https://user-images.githubusercontent.com/1177900/72795045-42d2bc00-3c3d-11ea-9da6-7c0b2e9aa02e.png)

Feel free to play around, maybe you will find some interesting way to make it work, but right now I think the auto-fill via accessibility services that Android Password Store is providing is the best thing we can have...

Will close the ticket since I don't think it's actionable, but do not hesitate to get back, ask some questions and run some ideas by us - and if you find something that might work, we will obviously reopen and consider 😉
