### ISSUE TITLE
Option to specify path to the password store?

### ISSUE THREAD

**Issue by axelsimon** [browserpass/browserpass-native#97]
### General information

-   Operating system + version: Fedora 32
-   Browser + version: Firefox 79.0
-   Information about the host app:
    -   How did you install it?
        Linux64 release package
    -   If installed an official release, put a version (`$ browserpass --version`): Browserpass host app version: 3.0.7
-   Information about the browser extension:
    -   How did you install it?
        addons.mozilla.org
    -   Browserpass extension version as reported by your browser: 3.5.0

---

### Exact steps to reproduce the problem

N/A

### What should happen?
There should be an option to tell `browserpass` where to find the password store, rather than it being hardcoded to `$HOME/.password-store/`.

Maybe there is by i didn't find in the README nor searching the issues.

### What happened instead?
`browserpass` can only use passwords located at `$HOME/.password-store/`, making it useless for those who keep their password on a removable drive, for instance.

**Comment by axelsimon** [comment]
Completely missed that second option, i was expecting it to be in the native sive. Thanks a lot @maximbaz, sorry for the noise.

**Comment by boscovn** [comment]
@maximbaz 
I do have $PASSWORD_STORE_DIR set, since I had to do it for configuring pass itself, but it's not working with the extension.
Editing the extension configs work, but since it's supposed to read the variable, I thought I'd mention it. Not sure wether the culprit is the extension or the native host, but in my case, I'm using the brave browser and the browserpass-darwin-arm64 native app (Using an M1 mac)

**Comment by maximbaz** [comment]
It's the browser who doesn't see your env var, as a GUI app it doesn't read your terminal config files like zshrc where you likely defined that variable. On Mac, you need to use `launchctl setenv`, or launch your browser from terminal.
